functional:
  - Сайт должен обеспечивать возможность поиска и просмотра продукции Garmin, включая навигационные устройства, спортивные часы, фитнес-трекеры и другие товары.
  - Пользователи должны иметь возможность ознакомиться с подробными характеристиками продукции Garmin, включая технические спецификации, описания функций и фотографии.
  - Сайт должен предоставлять информацию о новинках, акциях и скидках на продукцию Garmin.
  - Пользователи должны иметь возможность оформить заказ выбранных товаров через сайт, выбрав удобный способ доставки и оплаты.
  - Сайт должен обеспечивать возможность создания личного кабинета для пользователей с функциями просмотра истории заказов, управления данными профиля и подпиской на новости.
  - Пользователи должны иметь доступ к контактной информации для связи с представителями Garmin, включая онлайн-консультанта или форму обратной связи.
  - Сайт должен обеспечивать удобную навигацию по разделам и категориям продукции Garmin для быстрого поиска нужной информации.
  - Пользователи должны иметь возможность оценивать и оставлять отзывы о продукции Garmin на сайте.
  - Сайт должен быть адаптирован для работы на различных устройствах, включая компьютеры, планшеты и мобильные телефоны.

non-functional:
   - Загрузка страниц сайта должна быть быстрой и оптимизированной.
   - Сайт должен быть удобен для использования и навигации.
   - Сайт должен быть безопасным, защищенным от атак и утечек данных.
   - Поддержка различных браузеров (Chrome, Firefox, Safari, Edge) и операционных систем (Windows, MacOS, iOS, Android).
   - Сайт должен соответствовать стандартам доступности для людей с ограниченными возможностями.

     Требования к тестированию производительности:
   - Провести нагрузочное тестирование для определения максимальной нагрузки, которую сайт может выдержать без сбоев.
   - Проверить скорость загрузки страниц сайта при различных условиях интернет-соединения.
   - Проверить работоспособность сайта при большом количестве одновременных пользователей.

     Требования к тестированию безопасности:
   - Провести сканирование на уязвимости сайта.
   - Проверить защищенность личных данных пользователей.
   - Проверить соответствие сайта стандартам безопасности веб-приложений.

     Требования к тестированию совместимости:
   - Проверить работоспособность сайта на различных устройствах и разрешениях экранов.
   - Проверить корректность отображения сайта в различных браузерах.



